version: '3.8'

services:
  db:
    image: postgres:13
    container_name: tender_db
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d # Подключение папки с SQL-скриптами
    networks:
      - tender_network

  app:
    image: anabol1ks/tender-app:latest 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SERVER_ADDRESS=${SERVER_ADDRESS}
      - POSTGRES_CONN=${POSTGRES_CONN}
    depends_on:
      - db
    networks:
      - tender_network

volumes:
  db_data:

networks:
  tender_network:
    driver: bridge
